title: "iamvery.com"
description: "The work, thoughts, and ideas of Jay Hayes, a web developer."
url: http://iamvery.com
exclude: ["bin", "Gemfile", "Gemfile.lock", "README.md"]
highlighter: rouge
markdown: kramdown
plugins: [jekyll-gist]
